### ISSUE TITLE
OK NOW THERE ARE RACOONS BUT WHERE ARE THE BIRBS?

### ISSUE THREAD

**Issue by vedpadu** [DevSubmarine/SubBot#20]
I expect birbs or i honestly am going to be really disappointed with this 

Cock and baww towtuwe (CBT) is a sexuaw activity invowving appwication of pain ow constwiction to the mawe genyitaws. This may invowve diwectwy painfuw activities, such as wax pway, genyitaw spanking, squeezing, baww-busting, genyitaw fwogging, uwethwaw pway, tickwe towtuwe, ewotic ewectwostimuwation ow even kicking.[1] The wecipient of such activities may weceive diwect physicaw pweasuwe via masochism, ow emotionyaw pweasuwe thwough ewotic humiwiation, ow knyowwedge that the pway is pweasing to a sadistic dominyant. Many of these pwactices cawwy signyificant heawth wisks.​

**Comment by vedpadu** [comment]
I EXPECT TO SEE THIS ADDRESSED

**Comment by haaarshsingh** [comment]
Keep expecting 

![image](https://user-images.githubusercontent.com/69592270/93943330-4eacdb80-fd00-11ea-9291-5d94cf596b12.png)

**Comment by haaarshsingh** [comment]
No but seriously. 

![image](https://user-images.githubusercontent.com/69592270/93943628-eb6f7900-fd00-11ea-86d4-336b3ca19b71.png)

Here is an example of the `++img` command which can be used to get images from Google. I hope this satisfies you. 

P.S. - Be more formal with your requests next time.
